let projects = [
  {
    id: "clan",
    category: "web",
    title: "Clan africa",
    image: "/images/projects/clan.png",
    link: "https://www.clan.africa/",
    description: `Clan helps businesses & individuals offer point of need credit to consumers across Africa. Built with VueJS and Bootstrap`,
  },
  {
    id: "ileyah",
    category: "web",
    title: "Ileyah",
    image:
      "/images/projects/Ileyah-Rent-Now-Pay-Later-Pay-Rent-Instalmentally.png",
    link: "https://ileyah.com/",
    description: `Ileyah, is a revolutionary Fintech solution that allows people split their rent payments and make real estate ownership more accessible and manageable. 
    . Built with React, Next.js & Tailwind CSS`,
  },
  // {
  //   id: "jms",
  //   category: "web",
  //   title: "JMS",
  //   image: "/images/projects/JMS.png",
  //   link: "https://jms-frontend.vercel.app/",
  //   description: `JMS makes you explore world-class research articles from different journals and also give you access to prepare for SSCE. Built with React & Styled CSS`,
  // },
  // {
  //   id: "440-admin",
  //   category: "web",
  //   title: "440 Admin",
  //   image: "/images/projects/440-Admin.png",
  //   link: "https://440-admin.netlify.app/global-store-orders/jumia",
  //   description: `440 brings your market closer to you . Built with React & Tailwind`,
  // },
  // {
  //   id: 'zuri',
  //   category: 'web',
  //   title: 'Zuri',
  //   image: '/images/projects/Zuri.png',
  //   link: 'https://www.zuri.team/',
  //   description: ` Zuri is equipping youth with technological skills, fostering a supportive community, creating employment opportunities. Built with HTML and Tailwind CSS`,
  // },

  {
    id: "codygo-solution",
    category: "web",
    title: "Codygo Solution",
    image: "/images/projects/Codygo_solution.png",
    link: "https://codygo.com/",
    description: `Codygo is a cutting-edge technology provider delivering full-stack, AI-powered software solutions with a focus on scalability, transparency, and innovation. Specializing in cloud-first architectures, Codygo builds robust, multi-tenant applications and front-ends that integrate advanced AI capabilities, such as autonomous agents, fine-tuned models, and intelligent workflows.`,
  },
  {
    id: "Talentrek-ai",
    category: "web",
    title: "Talentrek.ai",
    image: "/images/projects/Talentrek.png",
    link: "https://talentrek.ai/",
    description: `A specialized assessment platform designed just for you – programmers and tech experts. Uncover your strengths, overcome challenges, and elevate your expertise with personalized feedback and real-time insights.`,
  },
  {
    id: "Suruhub",
    category: "web",
    title: "Suruhub",
    image: "/images/projects/Suruhub.png",
    link: "https://suruhub.com/",
    description: `SaaS e-commerce platform with intuitive store setup, warehouse/discount management, and scalable solutions for retailers, and drivers, it also offers a B2B system. Built with React Js, & Tailwind`,
  },
  {
    id: "Portfolio",
    category: "web",
    title: "My Portfolio",
    image: "/images/projects/Osomhe-Aleogho.png",
    link: "https://osomhe.netlify.app/",
    description: `This is an Application to showcase my some of my recent work. Built with Next Js, & Tailwind`,
  },
  {
    id: "Trendit³",
    category: "web",
    title: "Trendit³",
    image: "/images/projects/Trendit³.png",
    link: "https://www.trendit3.com/",
    description: `Trendit³ is a social finance platform that connects advertisers with earners. Advertisers are those who want to grow or boost their social media presence by posting tasks for earners to perform, such as following, resharing, liking, and commenting, etc. Earners are individuals who are paid for completing these simple tasks on their social media platforms. This was built with React Js, & Tailwind`,
  },
  {
    id: "2geda",
    category: "web",
    title: "2geda",
    image: "/images/projects/2GEDA.png",
    link: "https://2geda.net/",
    description: `This is a social media application which helps you also manage all you business, take annonymos vote and lots more in one place. This application is part of my recent work. Built with React Js,  Tailwind, & Redux`,
  },
];

export default projects
